"""Add weather table

Revision ID: 6f50e25fff23
Revises: 5e40d24fff22
Create Date: 2025-01-27 10:00:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6f50e25fff23"
down_revision = "5e40d24fff22"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "weather",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_weather_city"), "weather", ["city"], unique=False)
    op.create_index(op.f("ix_weather_date"), "weather", ["date"], unique=False)
    op.create_index(op.f("ix_weather_id"), "weather", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_weather_id"), table_name="weather")
    op.drop_index(op.f("ix_weather_date"), table_name="weather")
    op.drop_index(op.f("ix_weather_city"), table_name="weather")
    op.drop_table("weather")
    # ### end Alembic commands ###
