# Generated by Django 5.1.2 on 2024-11-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='rank',
            field=models.CharField(default=None, max_length=50, verbose_name='Звання'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='office',
            name='cabinet',
            field=models.CharField(max_length=10, unique=True, verbose_name='Кабінет №'),
        ),
        migrations.AlterField(
            model_name='office',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
    ]
